// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cart: typeof import('./src/components/Cart.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    Google: typeof import('./src/components/Google.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./src/components/SideMenu.vue')['default']
    Store: typeof import('./src/components/Store.vue')['default']
  }
}

export {}
